// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haqexjbktjitcpyipnoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcWV4amJrdGppdGNweWlwbm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjY5NjQsImV4cCI6MjA2ODUwMjk2NH0.W3F5-tE1k3-YzXHou6z2u9NIwIYJkGu__2vqx-rGbHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});